### ISSUE TITLE
Adjust fingerprint line in vCard format

### ISSUE THREAD

**Issue by wiktor-k** [juga0/opgpcard#2]
Hello,

I've been browsing examples and found this:

```
begin:vcard
fn:juga 
n:juga
email;internet:juga@riseup.net
key;pgp;http://pool.sks-keyservers.net:11371/pks/lookup?op=get&search=juga@riseup.net
OPENPGP4FPR:2DA81D01455C3A0032198850F305447AF806D46B
X-KADDRESSBOOK-OPENPGPFP:2DA81D01455C3A0032198850F305447AF806D46B
NOTE:vCard generate with opgpcard (https://github.com/juga0/opgpcard)
version:2.1
end:vcard
```

where `OPENPGP4FPR` URI is inserted directly as a new line. I think it would be more appropriate to use `KEY:OPENPGP4FPR:2DA81D01455C3A0032198850F305447AF806D46B` line instead.

RFC 6350 specifies [`KEY` field](https://tools.ietf.org/html/rfc6350#section-6.8.1) that, as a value, takes a URI. As `OPENPGP4FPR` is a [registered URI scheme](https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml) so I think `KEY:OPENPGP4FPR:...` is more appropriate.

For the record OpenKeychain supports QR-encoded fingerprints in this format: https://github.com/open-keychain/open-keychain/wiki/QR-Codes#vcard-support

**Comment by juga0** [comment]
Thanks @wiktor-k for reporting this. I followed your suggestion :)

**Comment by wiktor-k** [comment]
No problem :+1: glad to see someone using this thing, I thought I was the only one ;)
